- hosts: 127.0.0.1
  connection: local
  roles:
    - fileserver

  vars_files:
    - ./group_vars/fileserver

  tasks:
    - name: I will become a fileserver
      command: 'whoami'
      register: myidentity